name: sign_language_gp_app
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  audioplayers: ^6.0.0
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.16.1
  cupertino_icons: ^1.0.2
  dots_indicator: ^3.0.0
  firebase_core: ^2.29.0
  firebase_storage: ^11.0.15
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  font_awesome_flutter: ^10.7.0
  http: 1.1.0
  modal_progress_hud_nsn: ^0.5.1
  record: ^4.4.4
  scroll_loop_auto_scroll: ^0.0.5
  scrollable_positioned_list: ^0.3.8
  smooth_page_indicator: any
  speech_to_text: ^6.6.1
  video_player: ^2.2.14

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/applicationIcon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Medium.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
        - asset: assets/fonts/Cairo-Regular.ttf
