// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnt7X3FD6WsxiIF2CCrJ3fmHiMwNOedK0',
    appId: '1:1077191769175:web:164779b5b171053219b712',
    messagingSenderId: '1077191769175',
    projectId: 'sign-language-app-62656',
    authDomain: 'sign-language-app-62656.firebaseapp.com',
    storageBucket: 'sign-language-app-62656.appspot.com',
    measurementId: 'G-RXZ5B3P6R4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhq67hNgkJFyXE8MEXOIpdhlfzIZAVOo4',
    appId: '1:1077191769175:android:02831442ec569be219b712',
    messagingSenderId: '1077191769175',
    projectId: 'sign-language-app-62656',
    storageBucket: 'sign-language-app-62656.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDne40VUMB5yS--W1pCvy--nqU3WmbUPUo',
    appId: '1:1077191769175:ios:17e7fc9f1dc7d54019b712',
    messagingSenderId: '1077191769175',
    projectId: 'sign-language-app-62656',
    storageBucket: 'sign-language-app-62656.appspot.com',
    iosBundleId: 'com.example.signLanguageGpApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDne40VUMB5yS--W1pCvy--nqU3WmbUPUo',
    appId: '1:1077191769175:ios:17e7fc9f1dc7d54019b712',
    messagingSenderId: '1077191769175',
    projectId: 'sign-language-app-62656',
    storageBucket: 'sign-language-app-62656.appspot.com',
    iosBundleId: 'com.example.signLanguageGpApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnt7X3FD6WsxiIF2CCrJ3fmHiMwNOedK0',
    appId: '1:1077191769175:web:4818b7e6b106e67019b712',
    messagingSenderId: '1077191769175',
    projectId: 'sign-language-app-62656',
    authDomain: 'sign-language-app-62656.firebaseapp.com',
    storageBucket: 'sign-language-app-62656.appspot.com',
    measurementId: 'G-KRLZFWXMR0',
  );
}
